Static content generation for podcasts and videos
this-dot/modernweborg.github.io pull request #2
Opened 2016-11-29 23:01 UTC by jorgelainfiesta

2016-11-29 23:32 UTC, taras requested changes
Let's tag `ember-writer` to sha 81a96647b051658e808da0436a434f9698882edd

It'll require a few updates here.

2016-11-29 23:32 UTC, taras commented on app/adapters/application.js
> +export default DS.JSONAPIAdapter.extend(DS.BuildURLMixin, {
with the new version of `ember-writer`, you only need
`export { default } from 'ember-writer/adapters/application';`

2016-11-29 23:32 UTC, taras commented on app/models/author.js
> +import Model from 'ember-data/model';
With the new version of `ember-writer`, you can do this:
```js
import Author from 'ember-writer/models/author';

export default Author.extend({
  twitter: attr(),
  github: attr()
});
```

2016-11-29 23:32 UTC, taras commented on app/models/post.js
> +export default Model.extend({
With the new version of `ember-writer` you can do this:

```js
import Post from 'ember-writer/models/post';

export default Post.extend({
  mediaId: attr(),
  kind: attr(),
  section: attr(),
  imageUrl: attr()
});
```

2016-11-29 23:32 UTC, taras commented on app/models/tag.js
> +export default Model.extend({
You can delete this file with the new version of ember-writer

2016-11-29 23:32 UTC, taras commented on app/routes/application.js
> +    return hash({
You don't need to fetch everything anymore. You can just fetch exactly what you need for each route.

2016-11-30 14:54 UTC, jorgelainfiesta commented on app/routes/application.js
> +    return hash({
Is it possible to query data?

2016-11-30 15:16 UTC, jorgelainfiesta commented on app/routes/application.js
> +    return hash({
It seems not, but that's ok. Everything works like a charm :)

2016-11-30 15:24 UTC, taras commented
@jorgelainfiesta is this all ready to go?

2016-11-30 15:43 UTC, jorgelainfiesta commented
Yep

2016-11-30 15:43 UTC, merged

2016-11-30 15:43 UTC, taras commented on app/routes/application.js
> +    return hash({
right, we can't query but we can filter which should be enough.